name: Integration - pyautotester

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    name: Tests on ${{ matrix.python-version }}
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      ENV: dev
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python and Tox
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install requirements
        run: pip install pip-compile tox
      - name: Create requirements.txt
        run: pip-compile
      - name: Run tests using Tox
        run: tox -e py
